// var gulp = require('gulp'),
//     swig = require('gulp-swig'),
//     rename = require('gulp-rename'),
//     config = require('../../config').iconFonts;

// module.exports = function(codepoints, options) {
//     gulp.src(config.template)
//         .pipe(swig({
//             data: {
//                 icons: codepoints.map(function(icon) {
//                     return {
//                         name: icon.name,
//                         code: icon.codepoint.toString(16)
//                     }
//                 }),

//                 fontName: config.options.fontName,
//                 fontPath: config.fontPath,
//                 className: config.className,
//                 comment: 'DO NOT EDIT DIRECTLY!\n  Generated by gulp/tasks/iconFont.js\n  from ' + config.template
//             }
//         }))
//         .pipe(rename(config.stylOutputName))
//         .pipe(gulp.dest(config.stylDest));
// };